### ISSUE TITLE
Does not give me the result

### ISSUE THREAD

**Issue by Lancashire3000** [eirik-kjonstad/fortran-code-quality#2]
Hi,

  I git cloned your repository and run `python3 FortranQuality.py --path /path-to-folder-with-fortran-source-files/` (replace the path to my directory). I got

```

FortranQuality: a code-health tester for Fortran
(C) Eirik F. Kjønstad, 2021

Will analyze Fortran files in directory  (... my path...)
```

that's all. The path contains a couple of .f90 files. May I know how to get the result of analysis properly?

**Comment by eirik-kjonstad** [comment]
Hi, 

Thanks for trying out the code and posting the issue!

I think the issue was that the script only recognized files ending with ".F90" (with capitalized F). I have now added other common suffixes for modern Fortran code, including "f90". Hope it works now.

As a side note, the script is still rather simple and strict, and I would be happy to implement changes/improvements to make it more useful to other users. If you have suggestions, feel free to post more issues.

**Comment by eirik-kjonstad** [comment]
Assuming this is now resolved, and closing issue.
